version: "3.3"
services:

  pgadmin:
    ports:
      - "5050:5050"

  backend_api_gateway:
    ports:
      - "8000:8000"
    volumes:
      - ./backend_api_gateway/app:/app
    environment:
      - JUPYTER=jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.custom_display_url=http://127.0.0.1:8888
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    build:
      context: ./backend_api_gateway
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        INSTALL_JUPYTER: ${INSTALL_JUPYTER-true}
    # command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    command: /start-reload.sh

  backend_metrics:
    volumes:
      - ./metrics:/code/metrics
    ports:
      - "5000:5000"



  workspace_service:
    env_file:
      - ./workspace-service/.env
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    ports: 
      - "8001:8001"
    # volumes:
    #   - node_modules:/app/node_modules
    #   - ./workspace-service/src:/app/src
    build: 
      context: ./workspace-service
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}


volumes:
  app-db-data:
  node_modules:

networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false


